spring:
  application:
    name: cricket-api
  datasource:
    url: jdbc:mysql://localhost:3306/cricket
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

server:
  port: 8088


